services:
  mysql:
    image: mysql:8.0
    container_name: work_daily_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hassan0121
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "121:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DATABASE_URL: mysql+pymysql://root:hassan0121@mysql:3306/todo
    depends_on:
      - mysql

volumes:
  mysql_data:
